#!/bin/bash
# Assignment
# <VAR> op <EXPR>

# <VAR> = <EXPR>  assignment
((a=123))
echo "a = $a"

# <VAR> *= <EXPR> | <VAR> = <VAR> * <EXPR> 
# <VAR> /= <EXPR> | <VAR> = <VAR> / <EXPR> 
# <VAR> += <EXPR> | <VAR> = <VAR> + <EXPR> 
# <VAR> -= <EXPR> | <VAR> = <VAR> - <EXPR> 
# <VAR> %= <EXPR> | <VAR> = <VAR> % <EXPR> 
a=1
echo "a = $a"
((a=2))
echo "'$a * 2' = $a"
((a*=2))
echo "'$a * 2' = $a"
echo "a = $a"

# remainder (modulo)
a=10
echo "a = $a"
((a%=7))
echo "'a % 7' = $a"
((a%=2))
echo "'a % 2' = $a"
echo "a = $a"

# bitwise shifts
# <VAR> <<= <NUMBER> | <VAR> = <VAR> << <NUMBER>
# <VAR> >>= <NUMBER> | <VAR> = <VAR> >> <NUMBER>
echo "bitwise left shift"
a=2
echo "a = $a"
((a <<= 2)) # 0b0010(2) << 2 = 0b1000(8)
echo "'a << 2' = $a"
((a <<= 2)) # 0b0000_1000(8) << 2 = 0010_0000(32)
echo "'a << 2' = $a"
echo "a = $a"

echo "bitwise right shift"
a=16
echo "a = $a"
((a >>= 2)) # 0b0001_0000(16) >> 2 = 0b0000_0100(8)
echo "'a >> 2' = $a"
((a >>= 2)) # 0b0000_0100(8) >> 2 = 0b0000_0001(1)
echo "'a >> 2' = $a"
echo "a = $a"


# bitwise and or
# <VAR> &= <NUMBER> | <VAR> = <VAR> & <NUMBER>
# <VAR> |= <NUMBER> | <VAR> = <VAR> | <NUMBER>

echo "bitwise and(&)"
a=4 # 0b0010
temp=0
echo "a = $a"
temp=$a
((a &= 4)) # 0b0100(4) & 0b0100(4) = 0b0100(4)
echo "'$temp & 4' = $a"
temp=$a
((a &= 5)) # 0b0100(4) & 0b0101 = 0b0100(4)
echo "'$temp & 5' = $a"
temp=$a
((a &= 3)) # 0b0100(4) & 0b0011 = 0b0000(0)
echo "'$temp & 3' = $a"
echo "a = $a"

echo "bitwise or(|)"
a=4 # 0b0010
temp=0
echo "a = $a"
temp=$a
((a |= 4)) # 0b0100(4) | 0b0100(4) = 0b0100(4)
echo "'$temp | 4' = $a"
temp=$a
((a |= 5)) # 0b0100(4) | 0b0101 = 0b0101(5)
echo "'$temp | 5' = $a"
temp=$a
((a |= 3)) # 0b0101(5) | 0b0011 = 0b0111(7)
echo "'$temp | 3' = $a"
echo "a = $a"

# bitwise xor(^)
# 0 ^ 0 = 0
# 1 ^ 0 = 1
# 0 ^ 1 = 1
# 1 ^ 1 = 0
# <VAR> ^= <NUMBER> | <VAR> = <VAR> ^ <NUMBER>
echo "bitwise xor(^)"
a=4 # 0b0010
temp=0
echo "a = $a"
temp=$a
((a ^= 4)) # 0b0100(4) ^ 0b0100(4) = 0b0000(0)
echo "'$temp ^ 4' = $a"
temp=$a
((a ^= 5)) # 0b0000(0) ^ 0b0101(5) = 0b0101(5)
echo "'$temp ^ 5' = $a"
temp=$a
((a ^= 3)) # 0b0101(5) ^ 0b0011(3) = 0b0110(6)
echo "'$temp ^ 3' = $a"
echo "a = $a"