#!/bin/bash

# for el in list
# do
#   code here
# done


for var in 1st 2nd 3rd 4th 5th
do
echo The $var place
done

echo
echo

for var in "the second" "the third" "the fourth"
do
    echo "This is: $var"
done

echo
echo

file="../assets/countries.txt"
for country in $(cat $file)
do
echo " $country"
done

echo
echo

file="/etc/passwd"
IFS=$'\n'
for var in $(cat $file)
do
    echo $var
done

echo
echo

for((i=0; i < 10; i++))
do
    echo "i = $i"
done

echo
echo

var1=5
while [ $var1 -gt 0 ]
do
    echo $var1
    var1=$[ $var1 - 1 ]
done

